services:
  - type: web
    name: scrum-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: scrum-db
          property: connectionString
      - key: FLASK_ENV
        value: production

  - type: static
    name: scrum-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
